### ISSUE TITLE
Speed-up the validate phase

### ISSUE THREAD

**Issue by NooneBug** [nlpAThits/figet-hyperbolic-space#2]
Hi, 

I'm training your model using a different target space.

I'm noticing a very long computation time in the `validate-typing-dev-#` phase (15 minutes per epoch when the target space has 63 labeled vectors, 48 minutes when the types are approximately 200).

I know that in this phase the pyFLANN library is used an I think that is the Nearest Neighbor algorithm that slows down this phase.

Since the original dataset presents more than 8k types in the target space I think that you speed up this phase (or maybe I'm missing something in the code, but I didn't touch anything in the validation code) so I am here to ask if there is some method to speed up the training phase.

Thanks

**Comment by fedelopez77** [comment]
Hi,

In my case, with more than 8k labels, the training time of one epoch was 14 minutes, and the validation time was 7 minutes approximately. 

These times are from runs using one P40 GPU and at least 64 GB of RAM memory in the server. If you are not using GPUs to train the model, or you can't fit pyFLANN in memory, things will be much slower.
